package com.engineering.starter.config;

import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.pgvector.PgVectorEmbeddingStore;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import javax.sql.DataSource;

@Configuration
public class VectorStoreConfig {

    /**
     * Reuses the connection pool generated by Spring Data JPA automatically.
     */
    @Bean
    public EmbeddingStore<TextSegment> embeddingStore(DataSource dataSource) {
        return PgVectorEmbeddingStore.datasourceBuilder()
                .datasource(dataSource)
                .table("bpmn_knowledge_vectors") // Table identifier
                .dimension(1536)                 // Matches OpenAI's text-embedding-3-small profile
                .createTable(true)               // Executes native pgvector DDL automatically if missing
                .build();
    }
}
